### PR TITLE
return Access-Class in a RADIUS response

### PR DESCRIPTION
**Pull request by 0xAX**

### CODE REVIEW

**Comment by surik** [comment]
Hi @0xAX as you started working on radius provider what do you think about adding test suite like we already have for diameter?

**Comment by mgumz** [comment]
@0xAX whats the problem you are trying to solve with this change?

**Comment by RoadRunnr** [comment]
none of the projects that use ergw_aaa has a notion of an Access-Class, so why would this change be needed?

**Comment by 0xAX** [comment]
> Hi @0xAX as you started working on radius provider what do you think about adding test suite like we already have for diameter?

Yes, I will add as we talked.

@mgumz @RoadRunnr TPOSS sends Acess-Class in reply, so I need to know it to start sends interim updates or provision new balance

**Pull request closed without merging**
