### PR TITLE
Fix nodelay SCTP

### PR DESCRIPTION
**Pull request by vkatsuba**

### CODE REVIEW

**Review by RoadRunnr — COMMENTED** [review]
why don't you use proplists:unfold/1 ?

**Comment by vkatsuba** [comment]
> why don't you use proplists:unfold/1 ?

I don't want to bypass the list twice.

**Comment by RoadRunnr** [comment]
> > why don't you use proplists:unfold/1 ?
> 
> I don't want to bypass the list twice.

That code gets executed only during startup, there is no point in optimizing it to much. Just code for readability and not for speed in this case..

**Comment by vkatsuba** [comment]
> That code gets executed only during startup, there is no point in optimizing it to much. Just code for readability and not for speed in this case..

Ok, updated.

**Review by fholzhauser — APPROVED** [review]

**Pull request merged**
